server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://212.192.217.207:3306/germesplus
        username: server
        password: server
        driver-class-name: com.mysql.cj.jdbc.Driver
#        initialization-mode: always
        data: classpath:sql/data.sql

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQL8Dialect