name: Deploy docker image on server

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to server
        uses: shimataro/ssh-key-action@v2
        with:
           host: ${{ secrets.SSH_HOST }}
           username: ${{ secrets.SSH_USER }}
           password: ${{ secrets.SSH_PASSWORD }} 
           command: |
              sudo docker stop germes-plus || true
              sudo docker rm germes-plus || true
              sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/germes-plus:latest
              sudo docker run -d \
                --name germes-plus \
                -p 8080:8080 \
                ${{ secrets.DOCKER_HUB_USERNAME }}/germes-plus:latest
